import { UserRole } from '../common/enums/user-role.enum.js';
import { OrderStatus } from '../common/enums/order-status.enum.js';
import {
  UserEntity,
  RestaurantEntity,
  MenuItemEntity,
  OrderEntity,
  CourierEntity,
  ReviewEntity,
  PromotionEntity,
  SupportTicketEntity,
} from './entities.js';

export const INITIAL_USERS: UserEntity[] = [
  {
    id: 'usr-customer-1',
    role: UserRole.CUSTOMER,
    name: 'Sofia Lindqvist',
    phoneNumber: '+25163480570',
    email: 'sofia.l@example.com',
    addresses: [
      {
        id: 'addr-1',
        label: 'Home',
        street: 'Drottninggatan 14, Apt 4B',
        city: 'Stockholm',
        doorCode: '4820',
        isDefault: true,
      },
      {
        id: 'addr-2',
        label: 'Office',
        street: 'Bole Road, Mega Building 5th Fl',
        city: 'Addis Ababa',
        isDefault: false,
      },
    ],
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'usr-driver-1',
    role: UserRole.DRIVER,
    name: 'Lukas Vanhanen',
    phoneNumber: '+25163480570',
    email: 'lukas.rider@snabb.io',
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 'usr-restaurant-1',
    role: UserRole.RESTAURANT,
    name: 'Gustav Chef & Partner',
    email: 'owner@smashanddash.se',
    passwordHash: '$2a$10$wE04b...dummy', // mock pass: merchantPass2026!
    twoFactorSecret: '793421',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'usr-admin-1',
    role: UserRole.ADMIN,
    name: 'Super Admin Officer',
    email: 'admin@snabb.io',
    clearanceKey: 'SNABB-ROOT-KEY-2026',
    createdAt: new Date('2025-11-01'),
  },
];

export const INITIAL_RESTAURANTS: RestaurantEntity[] = [
  {
    id: 'smash',
    name: 'Smash & Dash Burgers',
    slug: 'smash-and-dash',
    cuisine: ['Burgers', 'American', 'Street Food'],
    rating: 4.9,
    reviewCount: 1840,
    deliveryTimeMin: 18,
    deliveryFee: 0,
    minOrder: 15.0,
    bannerImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    logoImage: 'logo.png',
    address: 'Kungsgatan 22, Stockholm',
    isOpen: true,
    isAcceptingOrders: true,
    prepTimeDefault: 15,
    tags: ['fast', 'freedel', 'toprated', 'halal'],
    lat: 59.3326,
    lng: 18.0649,
  },
  {
    id: 'nordic',
    name: 'Nordic Greens Bowl Co.',
    slug: 'nordic-greens',
    cuisine: ['Salads', 'Healthy', 'Vegan'],
    rating: 4.8,
    reviewCount: 920,
    deliveryTimeMin: 15,
    deliveryFee: 1.99,
    minOrder: 12.0,
    bannerImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    logoImage: 'logo.png',
    address: 'Götgatan 48, Stockholm',
    isOpen: true,
    isAcceptingOrders: true,
    prepTimeDefault: 12,
    tags: ['fast', 'vegan', 'toprated'],
    lat: 59.3149,
    lng: 18.0733,
  },
  {
    id: 'bella',
    name: 'Bella Italia Woodfire',
    slug: 'bella-italia',
    cuisine: ['Pizza', 'Italian', 'Pasta'],
    rating: 4.7,
    reviewCount: 1420,
    deliveryTimeMin: 25,
    deliveryFee: 0,
    minOrder: 18.0,
    bannerImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
    logoImage: 'logo.png',
    address: 'Vasagatan 11, Stockholm',
    isOpen: true,
    isAcceptingOrders: true,
    prepTimeDefault: 20,
    tags: ['freedel', 'toprated', 'deal'],
    lat: 59.3312,
    lng: 18.0588,
  },
  {
    id: 'habesha',
    name: 'Habesha Cultural Kitchen',
    slug: 'habesha-kitchen',
    cuisine: ['Ethiopian', 'Tibbs', 'Traditional'],
    rating: 4.95,
    reviewCount: 2150,
    deliveryTimeMin: 20,
    deliveryFee: 0,
    minOrder: 15.0,
    bannerImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    logoImage: 'logo.png',
    address: 'Bole Road, Near Edna Mall, Addis Ababa',
    isOpen: true,
    isAcceptingOrders: true,
    prepTimeDefault: 18,
    tags: ['fast', 'freedel', 'halal', 'toprated'],
    lat: 9.0054,
    lng: 38.7842,
  },
];

export const INITIAL_MENU_ITEMS: MenuItemEntity[] = [
  {
    id: 'dish-1',
    restaurantId: 'smash',
    name: 'Double Truffle Smash Burger',
    description: 'Two dry-aged smashed beef patties, black truffle mayo, smoked aged cheddar, crispy shallots, brioche.',
    price: 14.5,
    category: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    options: [
      {
        name: 'Patty Doneness',
        required: true,
        choices: [
          { name: 'Crispy Lacey Edge (Standard)', price: 0 },
          { name: 'Extra Well Done', price: 0 },
        ],
      },
      {
        name: 'Extra Add-ons',
        required: false,
        choices: [
          { name: 'Extra Patty & Cheese', price: 3.5 },
          { name: 'Applewood Smoked Bacon', price: 1.8 },
          { name: 'Gluten-free Brioche Bun', price: 1.0 },
        ],
      },
    ],
  },
  {
    id: 'dish-2',
    restaurantId: 'smash',
    name: 'Spicy Jalapeño Crunch Smash',
    description: 'Fresh grilled jalapeños, pepper jack cheese, chipotle crema, shredded iceberg on butter toasted bun.',
    price: 13.9,
    category: 'Burgers',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
  },
  {
    id: 'dish-3',
    restaurantId: 'smash',
    name: 'Rosemary Parmesan Crinkle Fries',
    description: 'Triple-cooked crinkle cuts dusted in coarse sea salt, rosemary, and 24-month Parmigiano Reggiano.',
    price: 4.9,
    category: 'Sides',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
    inStock: true,
  },
  {
    id: 'dish-4',
    restaurantId: 'smash',
    name: 'Salted Caramel Milkshake',
    description: 'Artisan soft serve blended with sea-salt caramel sauce and malted crunchies.',
    price: 5.5,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    inStock: true,
  },
];

export const INITIAL_ORDERS: OrderEntity[] = [
  {
    id: 'ord-101',
    orderNumber: '#SNB-9482',
    customerId: 'usr-customer-1',
    customerName: 'Sofia Lindqvist',
    customerPhone: '+25163480570',
    restaurantId: 'smash',
    restaurantName: 'Smash & Dash Burgers',
    courierId: 'courier-1',
    courierName: 'Lukas Vanhanen',
    courierPhone: '+25163480570',
    items: [
      { menuItemId: 'dish-1', name: 'Double Truffle Smash Burger', quantity: 2, price: 14.5 },
      { menuItemId: 'dish-3', name: 'Rosemary Parmesan Crinkle Fries', quantity: 1, price: 4.9 },
    ],
    subtotal: 33.9,
    deliveryFee: 0.0,
    tax: 4.07,
    tip: 3.0,
    discount: 5.0,
    total: 35.97,
    status: OrderStatus.IN_TRANSIT,
    prepTimeMinutes: 15,
    deliveryAddress: 'Drottninggatan 14, Apt 4B, Stockholm',
    dropOffNote: 'Ring door code 4820, leave outside apartment door.',
    currentLat: 59.334,
    currentLng: 18.062,
    destinationLat: 59.336,
    destinationLng: 18.061,
    timeline: [
      { status: OrderStatus.PENDING, timestamp: new Date(Date.now() - 25 * 60000) },
      { status: OrderStatus.ACCEPTED, timestamp: new Date(Date.now() - 22 * 60000) },
      { status: OrderStatus.PREPARING, timestamp: new Date(Date.now() - 18 * 60000) },
      { status: OrderStatus.READY_FOR_PICKUP, timestamp: new Date(Date.now() - 8 * 60000) },
      { status: OrderStatus.IN_TRANSIT, timestamp: new Date(Date.now() - 4 * 60000), note: 'Courier Lukas is en route' },
    ],
    paymentMethod: 'Credit Card (Visa •••• 4242)',
    isPaid: true,
    createdAt: new Date(Date.now() - 25 * 60000),
    updatedAt: new Date(Date.now() - 4 * 60000),
  },
  {
    id: 'ord-102',
    orderNumber: '#SNB-9483',
    customerId: 'usr-customer-1',
    customerName: 'Marcus Berg',
    customerPhone: '+25163480570',
    restaurantId: 'smash',
    restaurantName: 'Smash & Dash Burgers',
    items: [
      { menuItemId: 'dish-2', name: 'Spicy Jalapeño Crunch Smash', quantity: 1, price: 13.9 },
      { menuItemId: 'dish-4', name: 'Salted Caramel Milkshake', quantity: 1, price: 5.5 },
    ],
    subtotal: 19.4,
    deliveryFee: 1.99,
    tax: 2.33,
    tip: 2.0,
    discount: 0,
    total: 25.72,
    status: OrderStatus.PREPARING,
    prepTimeMinutes: 15,
    deliveryAddress: 'Sveavägen 45, Stockholm',
    destinationLat: 59.339,
    destinationLng: 18.058,
    timeline: [
      { status: OrderStatus.PENDING, timestamp: new Date(Date.now() - 10 * 60000) },
      { status: OrderStatus.ACCEPTED, timestamp: new Date(Date.now() - 8 * 60000) },
      { status: OrderStatus.PREPARING, timestamp: new Date(Date.now() - 5 * 60000) },
    ],
    paymentMethod: 'Apple Pay',
    isPaid: true,
    createdAt: new Date(Date.now() - 10 * 60000),
    updatedAt: new Date(Date.now() - 5 * 60000),
  },
];

export const INITIAL_COURIERS: CourierEntity[] = [
  {
    id: 'courier-1',
    userId: 'usr-driver-1',
    name: 'Lukas Vanhanen',
    phoneNumber: '+25163480570',
    vehicleType: 'E-Bike (Trek SuperCommuter)',
    licenseNumber: 'SE-99482-RIDER',
    isOnline: true,
    rating: 4.96,
    completedDeliveries: 418,
    earningsToday: 142.5,
    tipsToday: 28.0,
    currentLat: 59.334,
    currentLng: 18.062,
    activeOrderId: 'ord-101',
  },
];

export const INITIAL_REVIEWS: ReviewEntity[] = [
  {
    id: 'rev-1',
    restaurantId: 'smash',
    customerId: 'usr-customer-1',
    customerName: 'Mikael S.',
    rating: 5,
    comment: 'Best smash burgers in Stockholm hands down! Arrived piping hot, meat was wonderfully crispy on the edges.',
    merchantReply: 'Thank you Mikael! We take pride in our 200°C cast iron sear technique.',
    createdAt: new Date(Date.now() - 2 * 3600000),
  },
  {
    id: 'rev-2',
    restaurantId: 'smash',
    customerId: 'usr-customer-2',
    customerName: 'Elin V.',
    rating: 5,
    comment: 'Rosemary parmesan fries are addictive. Delivery was 12 mins faster than expected.',
    createdAt: new Date(Date.now() - 24 * 3600000),
  },
];

export const INITIAL_PROMOTIONS: PromotionEntity[] = [
  {
    id: 'promo-1',
    code: 'SUMMERBASH15',
    title: '15% Off Your Entire Feast',
    description: 'Valid on orders over $25 from partner kitchens.',
    discountPercent: 15,
    minOrderAmount: 25.0,
    active: true,
    usageCount: 148,
  },
  {
    id: 'promo-2',
    code: 'FREEDEL20',
    title: 'Zero Delivery Fee',
    description: 'Free courier drop-off within 5km radius.',
    discountPercent: 0,
    discountAmount: 2.99,
    minOrderAmount: 18.0,
    active: true,
    usageCount: 312,
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicketEntity[] = [
  {
    id: 'tkt-1',
    userId: 'usr-customer-1',
    userRole: UserRole.CUSTOMER,
    subject: 'Door code missing in rider GPS',
    message: 'The courier rang the main building bell because door code was not shown.',
    status: 'RESOLVED',
    priority: 'LOW',
    messages: [
      { sender: 'Customer', text: 'Door code was not shown to courier.', timestamp: new Date(Date.now() - 3600000) },
      { sender: 'Snabb Support', text: 'We have resolved this and pinned instructions to the courier navigation HUD.', timestamp: new Date() },
    ],
    createdAt: new Date(Date.now() - 3600000),
  },
];
